# Documentation: /docs/roles/bagisto.md

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755' 
  
- name: Clone Bagisto Docker repository
  git:
    repo: https://github.com/bagisto/bagisto-docker.git
    dest: /opt/bagisto 

- name: Start Bagisto containers
  command: docker-compose up -d
  args:
    chdir: /opt/bagisto

